#############################################################################
# Makefile for building: chart
# Generated by qmake (3.1) (Qt 5.15.0)
# Project:  ../chart/chart.pro
# Template: app
# Command: /opt/poky/3.1+snapshot/sysroots/x86_64-pokysdk-linux/usr/bin/qmake -o Makefile ../chart/chart.pro -spec linux-oe-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = arm-poky-linux-gnueabi-gcc -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a8 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security
CXX           = arm-poky-linux-gnueabi-g++ -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a8 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe --sysroot=/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe --sysroot=/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../chart -I. -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/QtWidgets -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/QtGui -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/QtCore -I. -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/linux-oe-g++
QMAKE         = /opt/poky/3.1+snapshot/sysroots/x86_64-pokysdk-linux/usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/poky/3.1+snapshot/sysroots/x86_64-pokysdk-linux/usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/poky/3.1+snapshot/sysroots/x86_64-pokysdk-linux/usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = chart1.0.0
DISTDIR = /home/amin/build-chart-beagle-Debug/.tmp/chart1.0.0
LINK          = arm-poky-linux-gnueabi-g++ -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a8 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security
LFLAGS        = --sysroot=/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi
LIBS          = $(SUBLIBS) -lm -lEGL /opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/libQt5Widgets.so /opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/libQt5Gui.so /opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/libQt5Core.so -lGLESv2 -lpthread   
AR            = cqs
RANLIB        = 
SED           = sed
STRIP         = arm-poky-linux-gnueabi-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../chart/main.cpp \
		../chart/mainwindow.cpp \
		../chart/pieview.cpp qrc_chart.cpp \
		moc_mainwindow.cpp \
		moc_pieview.cpp
OBJECTS       = main.o \
		mainwindow.o \
		pieview.o \
		qrc_chart.o \
		moc_mainwindow.o \
		moc_pieview.o
DIST          = /opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/spec_pre.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/unix.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/linux.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/sanitize.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/gcc-base.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/gcc-base-unix.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/g++-base.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/g++-unix.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/oe-device-extra.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/qdevice.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/device_config.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/qconfig.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3drender.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_charts.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_core.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_core_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_dbus.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_designer.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_gui.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_help.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_help_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_location.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_location_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_mqtt.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_mqtt_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_network.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_network_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_nfc.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_opengl.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_positioning.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qml.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quick.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_script.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_script_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_sensors.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serialport.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_sql.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_svg.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_testlib.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_uitools.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_websockets.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_widgets.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xml.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qt_functions.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qt_config.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/linux-oe-g++/qmake.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/spec_post.prf \
		../chart/.qmake.stash \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/exclusive_builds.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/toolchain.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/default_pre.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/resolve_config.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/default_post.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qml_debug.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/warn_on.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qt.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/resources_functions.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/resources.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/moc.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/unix/opengl.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/uic.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/unix/thread.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qmake_use.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/file_copies.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/testcase_targets.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/exceptions.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/yacc.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/lex.prf \
		../chart/chart.pro ../chart/mainwindow.h \
		../chart/pieview.h ../chart/main.cpp \
		../chart/mainwindow.cpp \
		../chart/pieview.cpp
QMAKE_TARGET  = chart
DESTDIR       = 
TARGET        = chart


first: all
####### Build rules

chart:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../chart/chart.pro /opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/linux-oe-g++/qmake.conf /opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/spec_pre.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/unix.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/linux.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/sanitize.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/gcc-base.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/gcc-base-unix.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/g++-base.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/g++-unix.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/oe-device-extra.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/qdevice.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/device_config.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/qconfig.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3drender.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_charts.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_core.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_core_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_dbus.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_designer.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_gui.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_help.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_help_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_location.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_location_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_mqtt.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_mqtt_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_network.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_network_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_nfc.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_opengl.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_positioning.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qml.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quick.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_script.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_script_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_sensors.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serialport.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_sql.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_svg.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_testlib.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_uitools.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_websockets.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_widgets.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xml.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qt_functions.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qt_config.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/linux-oe-g++/qmake.conf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/exclusive_builds.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/toolchain.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/default_pre.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/resolve_config.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/default_post.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qml_debug.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/warn_on.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qt.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/resources_functions.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/resources.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/moc.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/unix/opengl.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/uic.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/unix/thread.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qmake_use.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/file_copies.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/testcase_targets.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/exceptions.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/yacc.prf \
		/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/lex.prf \
		../chart/chart.pro \
		../chart/chart.qrc
	$(QMAKE) -o Makefile ../chart/chart.pro -spec linux-oe-g++ CONFIG+=debug CONFIG+=qml_debug
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/spec_pre.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/unix.conf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/linux.conf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/sanitize.conf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/gcc-base.conf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/gcc-base-unix.conf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/g++-base.conf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/common/g++-unix.conf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/oe-device-extra.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/qdevice.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/device_config.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/qconfig.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3danimation.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dcore.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dextras.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dinput.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquick.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3drender.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_charts.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_charts_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_concurrent.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_core.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_core_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_dbus.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_designer.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_designer_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_gui.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_gui_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_help.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_help_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_location.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_location_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_mqtt.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_mqtt_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimedia.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_network.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_network_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_nfc.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_opengl.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_positioning.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_printsupport.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_publishsubscribe.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qml.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qml_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmltest.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quick.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quick_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_script.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_script_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_scripttools.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_sensors.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serialbus.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serialport.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serviceframework.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_serviceframework_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_sql.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_sql_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_svg.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_svg_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_systeminfo.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_systeminfo_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_testlib.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_uitools.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_webchannel.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_websockets.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_widgets.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_x11extras.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xml.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xml_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qt_functions.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qt_config.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/linux-oe-g++/qmake.conf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/exclusive_builds.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/toolchain.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/default_pre.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/resolve_config.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/default_post.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qml_debug.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/warn_on.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qt.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/resources_functions.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/resources.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/moc.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/unix/opengl.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/uic.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/unix/thread.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/qmake_use.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/file_copies.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/testcase_targets.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/exceptions.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/yacc.prf:
/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/lex.prf:
../chart/chart.pro:
../chart/chart.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile ../chart/chart.pro -spec linux-oe-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile chart

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../chart/chart.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../chart/mainwindow.h ../chart/pieview.h $(DISTDIR)/
	$(COPY_FILE) --parents ../chart/main.cpp ../chart/mainwindow.cpp ../chart/pieview.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_chart.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_chart.cpp
qrc_chart.cpp: ../chart/chart.qrc \
		/opt/poky/3.1+snapshot/sysroots/x86_64-pokysdk-linux/usr/bin/rcc \
		../chart/qtdata.cht
	/opt/poky/3.1+snapshot/sysroots/x86_64-pokysdk-linux/usr/bin/rcc -name chart ../chart/chart.qrc -o qrc_chart.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/data/dummy.cpp
	arm-poky-linux-gnueabi-g++ -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a8 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -pipe --sysroot=/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi -g -Wall -Wextra -dM -E -o moc_predefs.h /opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_pieview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_pieview.cpp
moc_mainwindow.cpp: ../chart/mainwindow.h \
		moc_predefs.h \
		/opt/poky/3.1+snapshot/sysroots/x86_64-pokysdk-linux/usr/bin/moc
	/opt/poky/3.1+snapshot/sysroots/x86_64-pokysdk-linux/usr/bin/moc $(DEFINES) --include /home/amin/build-chart-beagle-Debug/moc_predefs.h -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/linux-oe-g++ -I/home/amin/chart -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/QtWidgets -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/QtGui -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/QtCore -I. -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/c++/10.1.0 -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/c++/10.1.0/arm-poky-linux-gnueabi -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/c++/10.1.0/backward -I/opt/poky/3.1+snapshot/sysroots/x86_64-pokysdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/10.1.0/include -I/opt/poky/3.1+snapshot/sysroots/x86_64-pokysdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/10.1.0/include-fixed -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include ../chart/mainwindow.h -o moc_mainwindow.cpp

moc_pieview.cpp: ../chart/pieview.h \
		moc_predefs.h \
		/opt/poky/3.1+snapshot/sysroots/x86_64-pokysdk-linux/usr/bin/moc
	/opt/poky/3.1+snapshot/sysroots/x86_64-pokysdk-linux/usr/bin/moc $(DEFINES) --include /home/amin/build-chart-beagle-Debug/moc_predefs.h -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/lib/mkspecs/linux-oe-g++ -I/home/amin/chart -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/QtWidgets -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/QtGui -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/QtCore -I. -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/c++/10.1.0 -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/c++/10.1.0/arm-poky-linux-gnueabi -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include/c++/10.1.0/backward -I/opt/poky/3.1+snapshot/sysroots/x86_64-pokysdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/10.1.0/include -I/opt/poky/3.1+snapshot/sysroots/x86_64-pokysdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/10.1.0/include-fixed -I/opt/poky/3.1+snapshot/sysroots/cortexa8hf-neon-poky-linux-gnueabi/usr/include ../chart/pieview.h -o moc_pieview.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: ../chart/main.cpp ../chart/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../chart/main.cpp

mainwindow.o: ../chart/mainwindow.cpp ../chart/pieview.h \
		../chart/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../chart/mainwindow.cpp

pieview.o: ../chart/pieview.cpp ../chart/pieview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pieview.o ../chart/pieview.cpp

qrc_chart.o: qrc_chart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_chart.o qrc_chart.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_pieview.o: moc_pieview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pieview.o moc_pieview.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/ || mkdir -p $(INSTALL_ROOT)/home/
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

